# Site settings
title: ModernTLD
description: > # this means to ignore newlines until "baseurl:"
    ModernTLD provides free domain registration on the OpenNIC network.
    Check out our site to learn more on how to connect to OpenNIC and
    get your very own domain for free!
url: "https://www.moderntld.com/"
baseurl: ""
logo: <b>ModernTLD</b>
paginate: 5
paginate_path: "/page:num/"
owner:
    email: jonah@moderntld.com
    facebook:
        show: false
        name: "Ichihara Rifa"
        url: "https://fb.me/nasya.aidan"
    github:
        show: true
        username: "ModernTLD"
    twitter:
        show: true
        username: "ModernTLD"
    disqus:
        show: true
        username: "jonaharagon"
sass:
    sass_dir: _sass
    style: compressed
permalink: pretty
markdown: kramdown
highlighter: rouge
gems:
    - jekyll-feed
    - jekyll-paginate
